# Generated by Django 4.2.4 on 2025-06-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('slot1', models.CharField(max_length=50)),
                ('slot2', models.CharField(max_length=50)),
                ('slot3', models.CharField(max_length=50)),
                ('slot4', models.CharField(max_length=50)),
                ('slot5', models.CharField(max_length=50)),
                ('slot6', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slot1', models.CharField(max_length=50)),
                ('slot2', models.CharField(max_length=50)),
                ('slot3', models.CharField(max_length=50)),
                ('slot4', models.CharField(max_length=50)),
                ('slot5', models.CharField(max_length=50)),
                ('slot6', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schedule.faculty'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule.student'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TimetableChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_number', models.PositiveSmallIntegerField(choices=[(1, 'Slot 1'), (2, 'Slot 2'), (3, 'Slot 3'), (4, 'Slot 4'), (5, 'Slot 5'), (6, 'Slot 6')])),
                ('course_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('added', 'Added'), ('cancelled', 'Cancelled')], max_length=10)),
            ],
            options={
                'unique_together': {('date', 'slot_number')},
            },
        ),
    ]
