# Generated by Django 4.2.4 on 2025-06-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_timetablecurrent_timetablemain_alter_course_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='schedule.timetablechange')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
            options={
                'unique_together': {('change', 'student')},
            },
        ),
    ]
